// ============================================
// Variant Form - نموذج إضافة/تعديل المتغير
// ============================================

'use client';

import { useState, useMemo, useRef, useCallback } from 'react';
import { motion } from 'framer-motion';
import {
  Package, Barcode, DollarSign, Archive, Image,
  Plus, X, Save, RefreshCw
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue
} from '@/components/ui/select';
import { toast } from 'sonner';
import type { VariantFormProps, VariantFormData } from '@/types/product-variant';

// Predefined attribute options
const predefinedAttributes = [
  { name: 'اللون', values: ['أحمر', 'أزرق', 'أخضر', 'أصفر', 'أسود', 'أبيض', 'رمادي', 'بني', 'برتقالي', 'بنفسجي'] },
  { name: 'الحجم', values: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'] },
  { name: 'المقاس', values: ['38', '40', '42', '44', '46', '48', '50'] },
  { name: 'الوزن', values: ['100g', '250g', '500g', '1kg', '2kg', '5kg'] },
  { name: 'السعة', values: ['100ml', '250ml', '500ml', '1L', '2L'] },
  { name: 'المادة', values: ['قطن', 'بوليستر', 'صوف', 'حرير', 'جلد', 'جينز'] },
];

// Helper function to get initial form data
function getInitialFormData(variant: VariantFormProps['variant'], defaultPrice: number, defaultCostPrice: number): VariantFormData {
  if (variant) {
    return {
      id: variant.id,
      productId: variant.productId,
      sku: variant.sku,
      name: variant.name,
      price: variant.price,
      costPrice: variant.costPrice,
      stock: variant.quantity,
      attributes: variant.attributes || [],
      barcode: variant.barcode || '',
      image: variant.image || '',
      isActive: variant.isActive
    };
  }
  return {
    sku: '',
    name: '',
    nameAr: '',
    price: defaultPrice,
    costPrice: defaultCostPrice,
    stock: 0,
    attributes: [],
    barcode: '',
    image: '',
    isActive: true
  };
}

export function VariantForm({
  variant,
  productId,
  onSubmit,
  onCancel,
  defaultPrice = 0,
  defaultCostPrice = 0
}: VariantFormProps) {
  const [formData, setFormData] = useState<VariantFormData>(() => 
    getInitialFormData(variant, defaultPrice, defaultCostPrice)
  );
  const [newAttributeName, setNewAttributeName] = useState('');
  const [newAttributeValue, setNewAttributeValue] = useState('');
  const [selectedAttribute, setSelectedAttribute] = useState('');
  const [selectedValue, setSelectedValue] = useState('');
  const [imagePreview, setImagePreview] = useState<string>(variant?.image || '');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Auto-generate name from attributes using useMemo
  const autoGeneratedName = useMemo(() => {
    if (formData.attributes.length > 0) {
      return formData.attributes.map(a => a.value).join(' - ');
    }
    return '';
  }, [formData.attributes]);

  // Handle image upload
  const handleImageChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = reader.result as string;
        setImagePreview(base64);
        setFormData(prev => ({ ...prev, image: base64 }));
      };
      reader.readAsDataURL(file);
    }
  }, []);

  // Add attribute
  const addAttribute = useCallback(() => {
    if (newAttributeName && newAttributeValue) {
      const existing = formData.attributes.find(a => a.name === newAttributeName);
      if (existing) {
        toast.error('هذه الخاصية موجودة بالفعل');
        return;
      }
      setFormData(prev => ({
        ...prev,
        attributes: [...prev.attributes, { name: newAttributeName, value: newAttributeValue }],
        name: prev.name || `${newAttributeName}: ${newAttributeValue}`
      }));
      setNewAttributeName('');
      setNewAttributeValue('');
    }
  }, [newAttributeName, newAttributeValue, formData.attributes]);

  // Add predefined attribute
  const addPredefinedAttribute = useCallback(() => {
    if (selectedAttribute && selectedValue) {
      const existing = formData.attributes.find(a => a.name === selectedAttribute);
      if (existing) {
        toast.error('هذه الخاصية موجودة بالفعل');
        return;
      }
      const newAttrs = [...formData.attributes, { name: selectedAttribute, value: selectedValue }];
      setFormData(prev => ({
        ...prev,
        attributes: newAttrs,
        name: newAttrs.map(a => a.value).join(' - ')
      }));
      setSelectedAttribute('');
      setSelectedValue('');
    }
  }, [selectedAttribute, selectedValue, formData.attributes]);

  // Remove attribute
  const removeAttribute = useCallback((index: number) => {
    setFormData(prev => {
      const newAttrs = prev.attributes.filter((_, i) => i !== index);
      return {
        ...prev,
        attributes: newAttrs,
        name: newAttrs.length > 0 ? newAttrs.map(a => a.value).join(' - ') : prev.name
      };
    });
  }, []);

  // Generate SKU automatically
  const generateSku = useCallback(() => {
    const timestamp = Date.now().toString(36).toUpperCase();
    const random = Math.random().toString(36).substring(2, 5).toUpperCase();
    const attrStr = formData.attributes.map(a => a.value.substring(0, 2)).join('');
    setFormData(prev => ({
      ...prev,
      sku: `${productId.substring(0, 4).toUpperCase()}-${attrStr}-${timestamp}-${random}`
    }));
  }, [productId, formData.attributes]);

  // Generate barcode
  const generateBarcode = useCallback(() => {
    const random = Math.floor(Math.random() * 10000000000000).toString().padStart(13, '0');
    setFormData(prev => ({ ...prev, barcode: random }));
  }, []);

  // Handle submit
  const handleSubmit = useCallback(() => {
    if (!formData.name.trim()) {
      toast.error('يرجى إدخال اسم المتغير');
      return;
    }
    if (formData.price <= 0) {
      toast.error('يرجى إدخال سعر صحيح');
      return;
    }
    onSubmit(formData);
  }, [formData, onSubmit]);

  // Get available predefined values
  const predefinedValues = useMemo(() => {
    const found = predefinedAttributes.find(a => a.name === selectedAttribute);
    return found?.values || [];
  }, [selectedAttribute]);

  return (
    <Card className="overflow-hidden">
      <CardHeader className="bg-gradient-to-l from-primary/10 to-transparent">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Package className="h-5 w-5 text-primary" />
          {variant ? 'تعديل المتغير' : 'إضافة متغير جديد'}
        </CardTitle>
      </CardHeader>
      
      <CardContent className="p-0">
        <ScrollArea className="h-[60vh]">
          <div className="p-6 space-y-6">
            {/* Image Upload */}
            <div className="flex gap-4">
              <div 
                className="w-24 h-24 rounded-lg border-2 border-dashed border-muted-foreground/30 flex items-center justify-center cursor-pointer overflow-hidden hover:border-primary/50 transition-colors"
                onClick={() => fileInputRef.current?.click()}
              >
                {imagePreview ? (
                  <img src={imagePreview} alt="صورة المتغير" className="w-full h-full object-cover" />
                ) : (
                  <div className="text-center text-muted-foreground">
                    <Image className="h-8 w-8 mx-auto mb-1" />
                    <span className="text-xs">رفع صورة</span>
                  </div>
                )}
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                className="hidden"
                onChange={handleImageChange}
              />
              <div className="flex-1 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label>SKU / رمز المنتج</Label>
                    <div className="flex gap-2">
                      <Input 
                        placeholder="SKU-001" 
                        value={formData.sku}
                        onChange={(e) => setFormData(prev => ({ ...prev, sku: e.target.value }))}
                      />
                      <Button variant="outline" size="icon" onClick={generateSku}>
                        <RefreshCw className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                  <div>
                    <Label>الباركود</Label>
                    <div className="flex gap-2">
                      <Input 
                        placeholder="1234567890123" 
                        value={formData.barcode}
                        onChange={(e) => setFormData(prev => ({ ...prev, barcode: e.target.value }))}
                      />
                      <Button variant="outline" size="icon" onClick={generateBarcode}>
                        <Barcode className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <Separator />

            {/* Basic Info */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>اسم المتغير *</Label>
                <Input 
                  placeholder={autoGeneratedName || "مثال: أحمر - XL"} 
                  value={formData.name}
                  onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                />
                {autoGeneratedName && formData.name === autoGeneratedName && (
                  <p className="text-xs text-muted-foreground mt-1">تم التوليد تلقائياً من الخصائص</p>
                )}
              </div>
              <div>
                <Label>الاسم (إنجليزي)</Label>
                <Input 
                  placeholder="Variant Name" 
                  value={formData.nameAr}
                  onChange={(e) => setFormData(prev => ({ ...prev, nameAr: e.target.value }))}
                />
              </div>
            </div>

            <Separator />

            {/* Attributes Section */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <Label className="text-base font-semibold">خصائص المتغير</Label>
                <Badge variant="secondary">{formData.attributes.length} خصائص</Badge>
              </div>

              {/* Existing Attributes */}
              {formData.attributes.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {formData.attributes.map((attr, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.9 }}
                    >
                      <Badge variant="outline" className="py-1.5 px-3 gap-1">
                        <span className="text-muted-foreground">{attr.name}:</span>
                        <span className="font-medium">{attr.value}</span>
                        <button 
                          onClick={() => removeAttribute(index)}
                          className="mr-1 hover:text-destructive"
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    </motion.div>
                  ))}
                </div>
              )}

              {/* Add Predefined Attribute */}
              <div className="grid grid-cols-3 gap-2">
                <Select value={selectedAttribute} onValueChange={setSelectedAttribute}>
                  <SelectTrigger>
                    <SelectValue placeholder="اختر الخاصية" />
                  </SelectTrigger>
                  <SelectContent>
                    {predefinedAttributes.map(attr => (
                      <SelectItem key={attr.name} value={attr.name}>{attr.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Select value={selectedValue} onValueChange={setSelectedValue}>
                  <SelectTrigger>
                    <SelectValue placeholder="اختر القيمة" />
                  </SelectTrigger>
                  <SelectContent>
                    {predefinedValues.map(val => (
                      <SelectItem key={val} value={val}>{val}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <Button variant="outline" onClick={addPredefinedAttribute} disabled={!selectedAttribute || !selectedValue}>
                  <Plus className="h-4 w-4 ml-1" /> إضافة
                </Button>
              </div>

              {/* Add Custom Attribute */}
              <div className="grid grid-cols-3 gap-2">
                <Input 
                  placeholder="اسم الخاصية (مثل: اللون)" 
                  value={newAttributeName}
                  onChange={(e) => setNewAttributeName(e.target.value)}
                />
                <Input 
                  placeholder="القيمة (مثل: أحمر)" 
                  value={newAttributeValue}
                  onChange={(e) => setNewAttributeValue(e.target.value)}
                />
                <Button variant="outline" onClick={addAttribute} disabled={!newAttributeName || !newAttributeValue}>
                  <Plus className="h-4 w-4 ml-1" /> إضافة
                </Button>
              </div>
            </div>

            <Separator />

            {/* Pricing */}
            <div className="space-y-4">
              <Label className="text-base font-semibold flex items-center gap-2">
                <DollarSign className="h-4 w-4" />
                التسعير والمخزون
              </Label>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <Label>سعر التكلفة</Label>
                  <Input 
                    type="number"
                    placeholder="0.00" 
                    value={formData.costPrice}
                    onChange={(e) => setFormData(prev => ({ ...prev, costPrice: parseFloat(e.target.value) || 0 }))}
                  />
                </div>
                <div>
                  <Label>سعر البيع *</Label>
                  <Input 
                    type="number"
                    placeholder="0.00" 
                    value={formData.price}
                    onChange={(e) => setFormData(prev => ({ ...prev, price: parseFloat(e.target.value) || 0 }))}
                    className="font-bold"
                  />
                </div>
                <div>
                  <Label>الكمية</Label>
                  <Input 
                    type="number"
                    placeholder="0" 
                    value={formData.stock}
                    onChange={(e) => setFormData(prev => ({ ...prev, stock: parseInt(e.target.value) || 0 }))}
                  />
                </div>
              </div>

              {/* Profit Preview */}
              {formData.price > 0 && (
                <div className="flex items-center gap-4 p-3 rounded-lg bg-muted/50">
                  <Archive className="h-4 w-4 text-muted-foreground" />
                  <div className="flex-1">
                    <span className="text-sm text-muted-foreground">الربح: </span>
                    <span className="font-bold text-emerald-600">
                      {(formData.price - formData.costPrice).toFixed(2)}
                    </span>
                    <span className="text-xs text-muted-foreground mr-2">
                      ({formData.costPrice > 0 ? (((formData.price - formData.costPrice) / formData.costPrice) * 100).toFixed(1) : 0}%)
                    </span>
                  </div>
                </div>
              )}
            </div>

            <Separator />

            {/* Active Toggle */}
            <div className="flex items-center justify-between">
              <div>
                <Label>حالة المتغير</Label>
                <p className="text-sm text-muted-foreground">المتغيرات غير النشطة لا تظهر في نقطة البيع</p>
              </div>
              <div className="flex items-center gap-2">
                <Switch 
                  checked={formData.isActive}
                  onCheckedChange={(checked) => setFormData(prev => ({ ...prev, isActive: checked }))}
                />
                <Label>{formData.isActive ? 'نشط' : 'غير نشط'}</Label>
              </div>
            </div>
          </div>
        </ScrollArea>

        {/* Actions */}
        <div className="flex items-center justify-end gap-3 p-4 border-t bg-muted/20">
          <Button variant="outline" onClick={onCancel}>
            إلغاء
          </Button>
          <Button onClick={handleSubmit} className="gap-2">
            <Save className="h-4 w-4" />
            حفظ المتغير
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

export default VariantForm;
